development:
  adapter: redis
  url: redis://localhost:6379/1

test:
  adapter: test

staging:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: <%= Rails.configuration.x.project_settings.slug %>_staging

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: <%= Rails.configuration.x.project_settings.slug %>_production
