name: Tests

on: [push]

jobs:
  test:
    if: "!contains(github.event.head_commit.message, '[skip-tests]')"
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Set up database
        run: |
          cp config/database.yml.ci config/database.yml
          RAILS_ENV=test bundle exec rails db:create
          RAILS_ENV=test bundle exec rails db:setup

      - name: Precompile assets
        run: RAILS_ENV=test bundle exec rails assets:precompile

      - name: Run RSpec tests
        run: |
          bundle exec rspec
